server:
  port: 8587

spring:
  application:
    name: gateway


  cloud:
    gateway:
      routes:
        - id: service_product
          uri: http://localhost:8585
          predicates:
            - Path= /products/**


        - id: service_customer
          uri: http://localhost:8586
          predicates:
            - Path= /customers/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka

#eureka.client.serviceUrl.defaultZone=http://localhost:9000/eureka