server:
  port: 8587

spring:
  application:
    name: gateway


  cloud:
    gateway:
      routes:
        - id: service_product
          uri: lb://productms
          predicates:
            - Path= /products/**


        - id: service_customer
          uri: lb://customerms
          predicates:
            - Path= /customers/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka

#eureka.client.serviceUrl.defaultZone=http://localhost:9000/eureka